Update docker_build_push.yml - don't run docker retag on scheduled runs
20treeAI/github-workflows pull request #41
Opened 2023-05-31 14:15 UTC by jessebot

2023-05-31 15:19 UTC, graphific commented
> Maybe a question I should've asked earlier: which Docker image is the one that needs the security fixes? The `latest` one? Or the `prod` one? This flow introduced here will update the `latest` and `stage` tagged Docker image only, IIUC.

At the moment its just the last image that gets pushed to a GCR repository, so tags are ignored at the moment by vanta. With snyk we can specify which tag to listen to. Will clarify with vanta if thats something we can do as well (I thought we could, but I couldnt find the setting).

2023-05-31 15:20 UTC, chanange approved these changes
Change is good, though the overall flow might not work unless I missed a PR to the dagster.yml. 

Scheduled run would rebuild the container and tag with stage though there would be no k8s rollout unless the rollout in the dagster.yml is also triggered. After deploying to stage I guess the code owners of the repo would need to create a new release which would have no changes in the release notes?

2023-05-31 20:39 UTC, chanange commented on .github/workflows/docker_build_push.yml
> -      - if: ${{ startsWith(github.ref, 'refs/tags/') }} || ${{ github.event_name == 'scheduled' }}
Just realised this is breaking the PR builds since this step is running see [failed build](https://github.com/20treeAI/risk_score/actions/runs/5137388475/jobs/9245406478)

Some things to be wary of with expressions in the `if` statement:
1. `${{ }}` are optional. It's automatically applied already according to the [docs](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#:~:text=When%20you%20use%20expressions%20in%20an%20if%20conditional%2C%20you%20may%20omit%20the%20expression%20syntax%20(%24%7B%7B%20%7D%7D)%20because%20GitHub%20automatically%20evaluates%20the%20if%20conditional%20as%20an%20expression.%20For%20more%20information%2C%20see%20%22Expressions.%22)
2. When evaluating expressions wrap the entire expression around the braces. For example this case should be:
```
${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'scheduled' }}
```

2023-05-31 20:42 UTC, chanange requested changes
Line 117 should be: 
```
if: !startsWith(github.ref, 'refs/tags/') || github.event_name == 'scheduled'
```

2023-06-01 07:51 UTC, chanange approved these changes

2023-06-01 07:51 UTC, merged